name: test
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make directory for htmlextra report
        run: mkdir -p testResults

      - name: Run postman collection using newman
        run: |
          newman run ./tests/postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html

      - name: Upload htmlextra report
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults
